name: terraform
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - "infra/**"

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ARM_USE_OIDC: true
      ARM_TENANT_ID: ${{ vars.AZ_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ vars.AZ_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ vars.AZ_GHA_CLIENT_ID }} # set this repo var to output azuread_application.gha.application_id after first apply, or hardcode
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          client-id: ${{ env.ARM_CLIENT_ID }}
          tenant-id: ${{ env.ARM_TENANT_ID }}
          subscription-id: ${{ env.ARM_SUBSCRIPTION_ID }}

      - uses: hashicorp/setup-terraform@v3
      - name: Terraform Init/Plan/Apply
        working-directory: infra
        run: |
          terraform init
          terraform plan -out tfplan
          terraform apply -auto-approve tfplan
